-- ==========================================================
-- CRAVINGS! · TARJETA DE LEALTAD · SUPABASE
-- Ejecuta TODO este archivo una sola vez en:
-- Supabase > SQL Editor > New query > Run
-- ==========================================================

create extension if not exists pgcrypto;

-- 1) TABLAS -------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text not null default '',
  public_code uuid not null unique default gen_random_uuid(),
  role text not null default 'customer' check (role in ('customer','employee','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.wallets (
  customer_id uuid primary key references public.profiles(id) on delete cascade,
  stamps smallint not null default 0 check (stamps between 0 and 6),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 50),
  employee_id uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  earned_from_purchase_id bigint unique references public.purchases(id) on delete set null,
  earned_at timestamptz not null default now(),
  redeemed_at timestamptz,
  redeemed_by uuid references public.profiles(id)
);

create index if not exists idx_purchases_customer_created on public.purchases(customer_id, created_at desc);
create index if not exists idx_rewards_customer_redeemed on public.rewards(customer_id, redeemed_at);

-- 2) CREAR PERFIL AUTOMÁTICAMENTE AL REGISTRARSE ------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', '')
  )
  on conflict (id) do nothing;

  insert into public.wallets (customer_id)
  values (new.id)
  on conflict (customer_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- 3) HELPERS DE SEGURIDAD ------------------------------------
create or replace function public.is_admin(p_uid uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = p_uid and p.role = 'admin'
  );
$$;

create or replace function public.is_staff(p_uid uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = p_uid and p.role in ('employee','admin')
  );
$$;

-- 4) RLS: CADA CLIENTE SÓLO VE SUS DATOS ---------------------
alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.purchases enable row level security;
alter table public.rewards enable row level security;

-- Limpiamos políticas si se vuelve a ejecutar el archivo.
drop policy if exists "profile own or admin" on public.profiles;
drop policy if exists "wallet own or admin" on public.wallets;
drop policy if exists "purchases own staff admin" on public.purchases;
drop policy if exists "rewards own or admin" on public.rewards;

create policy "profile own or admin"
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

create policy "wallet own or admin"
on public.wallets for select to authenticated
using (customer_id = auth.uid() or public.is_admin());

create policy "purchases own staff admin"
on public.purchases for select to authenticated
using (customer_id = auth.uid() or employee_id = auth.uid() or public.is_admin());

create policy "rewards own or admin"
on public.rewards for select to authenticated
using (customer_id = auth.uid() or public.is_admin());

-- No permitimos escrituras directas desde el navegador.
revoke insert, update, delete on public.profiles from anon, authenticated;
revoke insert, update, delete on public.wallets from anon, authenticated;
revoke insert, update, delete on public.purchases from anon, authenticated;
revoke insert, update, delete on public.rewards from anon, authenticated;

grant select on public.profiles, public.wallets, public.purchases, public.rewards to authenticated;

-- 5) EL EMPLEADO ESCANEA Y CONSULTA UNA TARJETA -------------
create or replace function public.lookup_customer(p_public_code uuid)
returns table (
  customer_id uuid,
  full_name text,
  stamps smallint,
  rewards_available bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_staff(auth.uid()) then
    raise exception 'No tienes permiso de empleado.';
  end if;

  return query
  select p.id, p.full_name, w.stamps,
    (select count(*) from public.rewards r where r.customer_id = p.id and r.redeemed_at is null)
  from public.profiles p
  join public.wallets w on w.customer_id = p.id
  where p.public_code = p_public_code and p.role = 'customer';
end;
$$;

-- 6) REGISTRAR COMPRA MÍNIMA DE $50 --------------------------
create or replace function public.register_purchase(p_public_code uuid, p_amount numeric)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer public.profiles%rowtype;
  v_wallet public.wallets%rowtype;
  v_purchase_id bigint;
  v_new_stamps integer;
  v_reward_earned boolean := false;
  v_rewards_available bigint;
begin
  if not public.is_staff(auth.uid()) then
    raise exception 'No tienes permiso de empleado.';
  end if;
  if p_amount is null or p_amount < 50 then
    raise exception 'La compra mínima para sumar un sello es de $50 MXN.';
  end if;

  select * into v_customer from public.profiles
  where public_code = p_public_code and role = 'customer';
  if not found then raise exception 'Tarjeta no encontrada.'; end if;

  select * into v_wallet from public.wallets
  where customer_id = v_customer.id
  for update;

  insert into public.purchases(customer_id, amount, employee_id)
  values (v_customer.id, p_amount, auth.uid())
  returning id into v_purchase_id;

  v_new_stamps := v_wallet.stamps + 1;
  if v_new_stamps >= 7 then
    v_new_stamps := 0;
    v_reward_earned := true;
    insert into public.rewards(customer_id, earned_from_purchase_id)
    values (v_customer.id, v_purchase_id);
  end if;

  update public.wallets
  set stamps = v_new_stamps, updated_at = now()
  where customer_id = v_customer.id;

  select count(*) into v_rewards_available
  from public.rewards where customer_id = v_customer.id and redeemed_at is null;

  return jsonb_build_object(
    'customer_name', v_customer.full_name,
    'stamps', v_new_stamps,
    'reward_earned', v_reward_earned,
    'rewards_available', v_rewards_available
  );
end;
$$;

-- 7) CANJEAR BEBIDA GRATIS -----------------------------------
create or replace function public.redeem_reward(p_public_code uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_id uuid;
  v_reward_id bigint;
begin
  if not public.is_staff(auth.uid()) then
    raise exception 'No tienes permiso de empleado.';
  end if;

  select id into v_customer_id from public.profiles
  where public_code = p_public_code and role = 'customer';
  if v_customer_id is null then raise exception 'Tarjeta no encontrada.'; end if;

  select id into v_reward_id
  from public.rewards
  where customer_id = v_customer_id and redeemed_at is null
  order by earned_at
  limit 1
  for update;

  if v_reward_id is null then raise exception 'Este cliente no tiene una bebida gratis disponible.'; end if;

  update public.rewards
  set redeemed_at = now(), redeemed_by = auth.uid()
  where id = v_reward_id;

  return jsonb_build_object('ok', true, 'reward_id', v_reward_id);
end;
$$;

-- 8) ADMIN: CAMBIAR ROL DE UNA CUENTA ------------------------
create or replace function public.admin_set_role(p_email text, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Sólo un administrador puede cambiar roles.';
  end if;
  if p_role not in ('customer','employee','admin') then
    raise exception 'Rol inválido.';
  end if;
  update public.profiles set role = p_role where lower(email) = lower(trim(p_email));
  if not found then raise exception 'No existe una cuenta con ese correo.'; end if;
end;
$$;

revoke all on function public.lookup_customer(uuid) from public;
revoke all on function public.register_purchase(uuid, numeric) from public;
revoke all on function public.redeem_reward(uuid) from public;
revoke all on function public.admin_set_role(text, text) from public;
grant execute on function public.lookup_customer(uuid) to authenticated;
grant execute on function public.register_purchase(uuid, numeric) to authenticated;
grant execute on function public.redeem_reward(uuid) to authenticated;
grant execute on function public.admin_set_role(text, text) to authenticated;

-- 9) REALTIME PARA QUE EL SELLO CAMBIE EN EL CELULAR --------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname='public' and tablename='wallets'
  ) then
    alter publication supabase_realtime add table public.wallets;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname='public' and tablename='rewards'
  ) then
    alter publication supabase_realtime add table public.rewards;
  end if;
end $$;

-- ==========================================================
-- DESPUÉS DE CREAR TU PRIMERA CUENTA EN EL SITIO, CONVIÉRTELA
-- EN ADMINISTRADOR EJECUTANDO ESTA LÍNEA POR SEPARADO:
--
-- update public.profiles set role='admin' where email='TU_CORREO@EJEMPLO.COM';
--
-- Cambia el correo por el tuyo.
-- ==========================================================
